[package]
name = "uniasset"
version = "0.8.0"
edition = "2024"

[dependencies]
serde = {  version = "1.0.219", features = ["derive"] }
serde_yaml_ng = "0.10.0"
walkdir = "2.5.0"
thiserror = "2.0.12"

[dev-dependencies]
anyhow = "1.0.98"